question_data = [
    {"text": "A slug's blood is green.", "answer": "True"},
    {"text": "The loudest animal is the African Elephant.", "answer": "False"},
    {"text": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
    {"text": "The total surface area of a human lungs is the size of a football pitch.", "answer": "True"},
    {
        "text": "In West Virginia, USA, if you accidentally hit an animal with your car, you are free to take it home to eat.",
        "answer": "True"},
    {"text": "In London, UK, if you happen to die in the House of Parliament, you are entitled to a state funeral.",
     "answer": "False"},
    {"text": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
    {"text": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
    {"text": "Google was originally called 'Backrub'.", "answer": "True"},
    {"text": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": "True"},
    {"text": "No piece of square dry paper can be folded in half more than 7 times.", "answer": "False"},
    {"text": "A few ounces of chocolate can to kill a small dog.", "answer": "True"}
]

open_trivia_db_questions = [
    {"category": "Geography",
     "type": "multiple",
     "difficulty": "medium",
     "question": "How many counties in the Republic of Ireland.",
     "correct_answer": "26",
     "incorrect_answers": ["32", "28", "30"]
     },
    {"category": "Entertainment: Music", "type": "boolean", "difficulty": "easy",
     "question": "Eurobeat is primarily an Italian genre of music.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Geography", "type": "multiple", "difficulty": "easy",
     "question": "What is the only state in the United States that does not have a flag in a shape with 4 edges?",
     "correct_answer": "Ohio",
     "incorrect_answers": ["Florida", "Idaho", "New Mexico"]},
    {"category": "Mythology", "type": "boolean", "difficulty": "easy",
     "question": "According to Greek Mythology, Zeus can control lightning.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Video Games", "type": "multiple",
     "difficulty": "easy",
     "question": "In Super Mario Bros., who informs Mario that the princess is in another castle?",
     "correct_answer": "Toad", "incorrect_answers": ["Luigi", "Yoshi", "Bowser"]},
    {"category": "Entertainment: Television", "type": "multiple",
     "difficulty": "medium",
     "question": "Which British writer wrote for both Doctor Who and Sherlock?",
     "correct_answer": "Steven Moffatt",
     "incorrect_answers": ["Phil Ford", "Russell T Davies", "Toby Whithouse"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "hard",
     "question": "Which product did Nokia, the telecommunications company, originally sell?",
     "correct_answer": "Paper",
     "incorrect_answers": ["Phones", "Computers", "Processors"]},
    {"category": "Animals", "type": "multiple", "difficulty": "medium",
     "question": "What is the collective noun for bears?", "correct_answer": "Sloth",
     "incorrect_answers": ["Drove", "Tribe", "Husk"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "hard",
     "question": "What was the name of the first Bulgarian personal computer?",
     "correct_answer": "IMKO-1",
     "incorrect_answers": ["Pravetz 82", "Pravetz 8D", "IZOT 1030"]},
    {"category": "Entertainment: Video Games", "type": "multiple",
     "difficulty": "medium",
     "question": "In Skylanders Giants, why was Zaps&#039; Wow Pow named &quot;For Riley&quot; ?",
     "correct_answer": "As a tribute to a fan who passed away",
     "incorrect_answers": ["As a reference to a film",
                           "After one of the writers of the game",
                           "After a voice actor"]}]
